# Generated by Django 4.0.3 on 2022-03-27 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e51bb4d0-1f95-4779-a462-bdb0b544ddef'), primary_key=True, serialize=False),
        ),
    ]
