# Generated by Django 4.0.3 on 2022-03-27 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_alter_project_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='username',
            new_name='usernames',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('aae630c4-63f4-4cbd-aef6-9c98262abf4c'), primary_key=True, serialize=False),
        ),
    ]
