# Generated by Django 4.0.3 on 2022-03-27 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_rename_username_project_usernames_todo_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e5003844-7a00-44f4-a8b1-087d36e00c5b'), primary_key=True, serialize=False),
        ),
    ]
