# Generated by Django 4.0.3 on 2022-03-27 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_alter_project_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9a5ab8f0-2fc1-4dac-bcc4-9bb13939d8e9'), primary_key=True, serialize=False),
        ),
    ]
