# Generated by Django 4.0.3 on 2022-04-05 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0005_alter_project_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1f98283c-7df5-4836-883d-3ef985793cc4'), primary_key=True, serialize=False),
        ),
    ]
