# Generated by Django 4.0.3 on 2022-03-04 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c986671a-1f99-46e2-9b02-96c40a5c2b37'), primary_key=True, serialize=False),
        ),
    ]
