# Generated by Django 4.0.2 on 2022-02-28 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f84b0f05-e5dd-48a1-bbc2-fd5f8cb25ec9'), primary_key=True, serialize=False),
        ),
    ]
