# Generated by Django 4.0.3 on 2022-03-04 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3371debf-0772-4fc3-b9ee-98aba48767ee'), primary_key=True, serialize=False),
        ),
    ]
