# Generated by Django 4.0.2 on 2022-02-28 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_remove_user_id_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a0234dc6-a4e1-4ad2-a263-e4b26923cd9e'), primary_key=True, serialize=False),
        ),
    ]
