# Generated by Django 4.0.3 on 2022-03-24 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c0f6d7c5-354b-48f2-899a-d17271e637f6'), primary_key=True, serialize=False),
        ),
    ]
