# Generated by Django 4.0.3 on 2022-03-27 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_user_options_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6c2402ee-8b87-4bda-91d5-22df39dea74d'), primary_key=True, serialize=False),
        ),
    ]
