# Generated by Django 4.0.3 on 2022-03-27 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('420ce9b7-aa87-4ad4-bf19-a2903b0510e2'), primary_key=True, serialize=False),
        ),
    ]
