# Generated by Django 4.0.3 on 2022-03-27 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0006_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('349500bc-c3f6-4020-8005-edffbb2444a9'), primary_key=True, serialize=False),
        ),
    ]
