# Generated by Django 4.0.3 on 2022-03-27 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0007_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7138afef-ae30-4c02-8b9f-441162797ee1'), primary_key=True, serialize=False),
        ),
    ]
