# Generated by Django 4.0.3 on 2022-04-05 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7168f515-85cb-477b-8b4a-b81d864cf0e2'), primary_key=True, serialize=False),
        ),
    ]
